apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrastructure-flux
  namespace: infrastructure
  labels:
    toolkit.fluxcd.io/tenant: infrastructure

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-limited-account
  namespace: infrastructure
rules:
- apiGroups:
  - 'helm.toolkit.fluxcd.io'
  - 'source.toolkit.fluxcd.io'
  resources:
  - helmreleases
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - 'source.toolkit.fluxcd.io'
  resources:
  - helmrepositories
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - services
  - serviceaccounts
  - clusterroles
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - clusterroles
  - rolebindings
  - clusterrolebindings
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - deployments/status
  - replicasets
  - statefulsets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - 'build.openshift.io'
  resources:
  - builds
  - buildconfigs
  - buildconfigs/instantiate
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - 'events.k8s.io'
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - 'image.openshift.io'
  resources:
  - imagestreams
  verbs:
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - 'route.openshift.io'
  resources:
  - routes
  - routes/custom-host
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - 'kafka.strimzi.io'
  resources:
  - kafkatopics
  - kafkatopics/status
  - kafkausers
  - kafkausers/status
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - 'kafka.strimzi.io'
  resources:
  - kafkas
  - kafkaconnects
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infrastructure-flux
  namespace: infrastructure
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-limited-account
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:infrastructure:reconciler
- kind: ServiceAccount
  name: infrastructure-flux
  namespace: infrastructure
- kind: Group
  name: flux
  namespace: infrastructure

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infrastructure-flux
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-limited-account
subjects:
- kind: ServiceAccount
  name: infrastructure-flux
  namespace: infrastructure