apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: infrastructure
  namespace: infrastructure
spec:
  interval: 1m0s
  ref:
    branch: dev
  secretRef:
    name: infrastructure-git-flux
  url: ssh://git@github.com/deyanstoyanov10/infrastructure

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: infrastructure
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: infrastructure-flux
  sourceRef:
    kind: GitRepository
    name: infrastructure
  targetNamespace: infrastructure