apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: infrastructure
  namespace: infrastructure
spec:
  interval: 1m0s
  url: https://github.com/deyanstoyanov10/infrastructure
  ref:
    branch: dev

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: infrastructure
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: infrastructure-flux
  sourceRef:
    kind: GitRepository
    name: infrastructure
  targetNamespace: infrastructure